apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-simple-app
  name: my-simple-app
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-simple-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}